// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/assistant.ts.
// Do not edit: change the Simplified text there and re-run the script.

export const assistantMessages = {
    assistantPage: {
      kicker: "助理",
      title: "車隊助理",
      copy: "問今天的行程、訂單衝突、收入,或者還沒回復的 Turo 訊息。助理基於你的實時車隊資料回答,也能幫你起草訊息——但它不會傳送任何東西,也不會改動任何記錄。",
      emptyState: "關於車隊的問題都可以問。回答來自你的實時資料,不是模型的猜測。",
      suggest1: "今天有什麼安排?",
      suggest2: "有需要處理的訂單衝突嗎?",
      suggest3: "哪些 Turo 訊息需要回復?",
      suggest4: "這個月收入多少?",
      inputPlaceholder: "問點關於車隊的事…",
      send: "傳送",
      sending: "傳送中…",
      thinking: "正在查你的車隊資料…",
      groundedIn: (vehicles: number, trips: number, conflicts: number, emails: number) =>
        `依據:${vehicles} 台車 · 本週 ${trips} 單行程 · ${conflicts} 個衝突 · ${emails} 封未讀 Turo 郵件`,
      errorGeneric: "助理暫時無法回答,請稍後再試。",
      errorRateLimited: "短時間內問得太多了,歇一分鐘。",
      errorNotConfigured: "這個部署還沒有配置助理。",
      notConfiguredHint:
        "在環境變數裡設定 KIMI_API_KEY 以啟用助理。到 platform.moonshot.ai 申請金鑰。",
      alertsTitle: "提醒",
      alertsCopy: "由程式碼檢測,不是模型猜的。條件消失後提醒會自動關閉。",
      alertsScan: "重新掃描",
      alertsScanning: "掃描中…",
      alertsEmpty: "目前沒有需要你處理的事。",
      alertsOpen: "檢視",
      alertsAcknowledge: "知道了",
      inboxTitle: "Turo 收件箱",
      inboxCopy: "Turo 發給你的郵件,自動收取並按是否需要回復排序。",
      inboxEmpty: "還沒有 Turo 郵件。Gmail 同步跑過之後會出現在這裡。",
      inboxNotConfigured:
        "設定 GMAIL_IMAP_USER 和 GMAIL_IMAP_PASSWORD(Gmail 應用專用密碼)以自動收取 Turo 通知。",
      needsReply: "待回覆",
      syncNow: "立即同步",
      syncing: "同步中…",
      syncFailed: "同步失敗,請檢查 Gmail 設定。",
      syncedCount: (imported: number) =>
        imported === 0 ? "沒有新的 Turo 郵件。" : `收取了 ${imported} 封新的 Turo 郵件。`,
    },
  } as const;
