// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/booking.ts.
// Do not edit: change the Simplified text there and re-run the script.

export const bookingMessages = {
    bookingPage: {
      notFoundTitle: "找不到這個預訂",
      notFoundCopy: "這個連結已失效。如果你還留著確認郵件，請核對地址，或者直接聯絡車主。",
      kicker: "你的預訂",
      referenceLabel: "訂單號",
      pickupLabel: "取車",
      returnLabel: "還車",
      statusLabel: "狀態",
      paidLabel: "已付",
      outstandingLabel: "待付",
      depositLabel: "押金",
      scheduleTitle: "付款計劃",
      schedulePaid: "已付",
      scheduleDue: "應付",
      cancelledNotice: "這個預訂已取消。",

      pendingTitle: "申請已收到",
      pendingCancel: "你提交了取消申請，車主會與你聯絡。",
      pendingReschedule: (from: string, to: string) =>
        `你申請把預訂改到 ${from} – ${to}，車主會與你聯絡。`,
      declinedNotice: "你上一次的申請被拒絕了。需要溝通請聯絡車主。",

      changeTitle: "需要改動？",
      changeCopy: "提交申請，由車主確認。",
      cancelHeading: "取消這個預訂",
      cancelFreeCopy: (amount: string) => `現在取消可全額退還 ${amount}。`,
      cancelLateCopy: (refund: string, penalty: string) =>
        `距取車不到 48 小時，需扣一天租金（${penalty}），可退還 ${refund}。`,
      cancelStartedCopy: "這個預訂已經開始，無法在此取消，請聯絡車主。",
      cancelAction: "申請取消",
      cancelConfirm: "確定嗎？系統會向車主提交取消申請。",

      rescheduleHeading: "更改日期",
      rescheduleCopy: "選擇你希望的新日期。差價與車主結算。",
      newPickupLabel: "新取車日",
      newReturnLabel: "新還車日",
      rescheduleAction: "申請新日期",
      rescheduleUnavailable: "該時段這輛車已被預訂，請換一個時間。",
      noteLabel: "想讓車主知道的事",
      notePlaceholder: "選填",

      invalidRange: "還車日期必須晚於取車日期。",
      submitError: "申請沒能提交，請重試。",
      helpTitle: "聯絡車主",
    },
    bookingRequestsPage: {
      title: "變更申請",
      empty: "還沒有租客提出變更。",
      kindCancel: "取消",
      kindReschedule: "改期",
      requestedLabel: "申請於",
      quotedRefundLabel: "按政策應退",
      approveAction: "同意",
      declineAction: "拒絕",
      approvedLabel: "已同意",
      declinedLabel: "已拒絕",
      refundedLabel: "已退款",
      refundFailed: "退款沒能發出，請到 Stripe 檢視後重試。",
      conflictBlocked: "這些日期已經不空了，無法批准。",
    },
  } as const;
