// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/contact.ts.
// Do not edit: change the Simplified text there and re-run the script.

export const contactMessages = {
    contact: {
      trigger: "聯絡我們",
      modalTitle: "反饋或諮詢",
      modalSubtitle: "聯絡開發者",
      fromLabel: "發件人",
      messageLabel: "留言",
      messagePlaceholder:
        "描述一下發生了什麼、你預期是什麼樣、出問題的頁面是哪個。截圖能幫上很大的忙。",
      attachLabel: "附件",
      attachHint: "最多 5 個檔案，每個 ≤ 10 MB，總共 ≤ 25 MB。支援圖片、影片、PDF。",
      filesSelected: (count: number, sizeMb: string) =>
        count === 0 ? "新增檔案" : `${count} 個檔案 · ${sizeMb} MB`,
      removeFile: "移除",
      sendAction: "傳送",
      sendingAction: "傳送中…",
      cancelAction: "取消",
      closeLabel: "關閉",
      successTitle: "已傳送",
      successCopy: "感謝反饋！我們收到後會儘快回覆到你帳號繫結的郵箱。",
      errorGeneric: "傳送失敗，請稍後重試。",
      errorMessageTooShort: "請用幾句話描述一下情況，方便我們幫你定位問題。",
      errorTooManyFiles: (max: number) => `每次最多上傳 ${max} 個檔案。`,
      errorFileTooLarge: (filename: string, mb: number) =>
        filename ? `${filename} 超過單檔案 ${mb} MB 上限。` : `有檔案超過單檔案 ${mb} MB 上限。`,
      errorFileType: "暫不支援這種檔案型別，請換圖片、影片或 PDF。",
      errorTotalTooLarge: (mb: number) =>
        `總大小超過 ${mb} MB，請刪除一個檔案或先壓縮後再發。`,
      errorNotConfigured: "本服務暫未配置反饋郵箱，請直接聯絡運營者。",
    },
  } as const;
