// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/imports.ts.
// Do not edit: change the Simplified text there and re-run the script.

export const importsMessages = {
    imports: {
      guideTitle: "匯入步驟",
      guideSteps: [
        {
          title: "從 Turo 下載 CSV",
          body: "開啟 Turo 的 Earnings 頁面，選擇你想匯入的時間範圍，點選 Export 把 CSV 下載到電腦。",
        },
        {
          title: "確認名額夠用",
          body: "先看右側「當前可用總名額」是否覆蓋車隊數量。不夠的話，先去購買更多名額或輸入 coupon 解鎖。",
        },
        {
          title: "選擇檔案和帳戶",
          body: "選擇 CSV，再選它是從哪個 Turo 帳戶匯出的。檔案裡的每一列都會讀入；Reservation ID 用來判斷訂單是不是已經匯入過。",
        },
        {
          title: "執行匯入",
          body: "點選「開始匯入」。車隊裡沒有的車會先列出來讓你確認，再新建；與線下訂單衝突的記錄會被標記等你處理。",
        },
      ],
      unconfirmedKicker: "需要核對",
      unconfirmedTitle: (count: number) => `${count} 個即將開始的訂單,車輛未經車牌確認`,
      unconfirmedCopy:
        "預訂郵件裡只有車型,從來沒有車牌,所以這些訂單的車輛是拿車型去車隊裡匹配出來的。只有在車隊完整時這才成立:如果真正那台車不在車隊裡,車型仍然可能唯一匹配到另一台車——錯的那台——而結果看上去和正確答案沒有任何區別。匯入覆蓋這些日期的 CSV,車牌就能定案。",
      unconfirmedSiblings: (count: number) => `車隊裡有 ${count} 台同款同年份`,
      unconfirmedUnknownVehicles: (list: string) =>
        `以前的匯入裡出現過車隊中沒有的車:${list}。只要它們不在車隊裡,這些車型的預訂郵件能匹配到的車就比實際少一台,就可能落到錯誤的車上。重新匯入那份檔案，確認它列出的新車，或者手動把它們加進來。`,
      unconfirmedShowList: (count: number) => `檢視這 ${count} 筆`,
      logShowAll: (count: number) => `顯示更早的 ${count} 次匯入`,
      logKicker: "匯入日誌",
      logTitle: "最近 CSV 批次",
      sampleFile: "示例檔案位於 `/sample-data/turo-sample.csv`",
      table: {
        file: "檔案",
        importedBy: "匯入人",
        importedAt: "匯入時間",
        rows: "行數",
        result: "結果",
        batchResult: (successRows: number, failedRows: number) =>
          `${successRows} 成功 / ${failedRows} 失敗`,
      },
      panel: {
        uploadTitle: "選擇 Turo CSV 檔案",
        uploadHint: "Turo 收入頁匯出的 CSV。檔案裡的每一列都會存進對應的訂單。",
        openTuroPage: "開啟 Turo 下載頁",
        chooseFile: "選擇檔案",
        chooseAnother: "換一個檔案",
        reading: "正在讀取檔案…",
        fileSummary: (rows: number, cars: number, range: string) =>
          `${rows} 行 · ${cars} 台車${range ? ` · ${range}` : ""}`,
        previewToggle: (columns: number) => `檢視檔案內容（前 5 行，共 ${columns} 列）`,
        notTuroFile: (missing: string) =>
          `這份檔案不像 Turo 收入匯出：找不到「${missing}」列。請從 Turo 收入頁重新匯出。`,
        parseFailed: "檔案讀不出來，請確認是 CSV 格式。",
        oneVehicleIdentifier: "車輛",
        accountStep: "這份檔案屬於哪個 Turo 帳戶？",
        turoAccountHint:
          "一份匯出只包含一個帳戶的車。選錯了，這些車會記到別的帳戶下，之後再也匹配不上自己的 Turo 郵件。",
        turoAccountPlaceholder: "例如 kevin",
        turoAccountMain: "主帳戶",
        turoAccountOther: "其他帳戶…",
        importStep: "開始匯入",
        importStepHint: "如果有車隊裡沒有的車，會先列出來讓你確認，再新建。",
        runImport: "開始匯入",
        needsFile: "先選擇檔案",
        needsAccount: "先選擇帳戶",
        progressSteps: ["讀取檔案", "核對車輛", "匯入訂單"],
        progressNote: (rows: number) => `共 ${rows} 行，檔案大要幾十秒，請不要重新整理或關閉頁面`,
        newVehiclesKicker: "發現新車",
        newVehiclesTitle: (count: number) => `這份檔案裡有 ${count} 台車隊裡還沒有的車`,
        newVehiclesCopy:
          "勾選的車會新建，並把它們的訂單一起匯入。沒勾的車，訂單這次先不匯入；以後把車加上，再匯入同一份檔案就行。",
        newVehiclesQuota: (count: number) =>
          count === 0
            ? "當前名額已用完，不能再加車。要新增這些車，請先購買名額。"
            : `當前名額只夠再加 ${count} 台。要加更多，請先購買名額。`,
        newVehicleTrips: (count: number) => `${count} 筆訂單`,
        confirmCreate: (count: number) => `新增 ${count} 台並匯入`,
        skipCreate: "不新增，只匯入已有車輛",
        cancel: "取消",
        genericFailure: "匯入失敗",
        importSuccessTitle: "匯入完成",
        importFailureTitle: "匯入失敗",
        importAlertClose: "關閉",
        failureBreakdown: "失敗原因分類",
        failureRows: (count: number) => `${count} 行`,
        failureSampleRows: "示例行號",
        billing: {
          kicker: "0. 訂閱計費",
          title: "車輛名額訂閱",
          copy: "前 5 台車輛免費。超過後，每多 1 台車輛收費 $1 USD / 月。只有已購買名額覆蓋車輛總數後，才允許匯入 CSV。",
          currentVehicles: "當前車輛數",
          freeIncluded: "免費名額",
          paidSlots: "已付費名額",
          allowedTotal: "當前可用總名額",
          subscriptionStatus: "訂閱狀態",
          desiredSlots: "想購買的車輛名額數",
          priceHint: (value: string) => `超出免費 5 台後的月費：${value}`,
          payAction: "前往 Stripe 支付",
          manageAction: "去 Stripe 修改名額",
          redirecting: "正在跳轉到 Stripe...",
          notConfigured: "Stripe 計費尚未配置，暫時無法啟用這個功能。",
          genericError: "暫時無法發起支付，請稍後再試。",
          projectionTitle: "匯入前計費檢查",
          projectedVehicles: (count: number) => `匯入後預計車輛數：${count}`,
          projectedNewVehicles: (count: number) => `本次檔案新增車輛數：${count}`,
          projectedPaidSlots: (count: number) => `匯入後所需付費名額：${count}`,
          checkingImport: "正在檢查這份 CSV 是否超過已購車輛名額...",
          limitExceeded: "車輛數量將超過當前已購名額，請先補交費用再匯入。",
          limitExceededDetail: (projected: number, allowed: number, extra: number) =>
            `這份 CSV 會讓車輛總數達到 ${projected} 台，但你當前只允許 ${allowed} 台。請先補購 ${extra} 個付費名額。`,
          modalKicker: "需要補交費用",
          modalTitle: "購買更多車輛名額",
          modalCopy: (projected: number, allowed: number) =>
            `這次匯入會讓你的車輛總數達到 ${projected} 台，而當前已付費上限只支援 ${allowed} 台。請先完成支付，再重新執行匯入。`,
          projectedVehiclesLabel: "預計匯入後車輛數",
          additionalNeededLabel: "還需補購名額",
          modalPriceHint: (value: string) => `迴圈月費：${value}`,
          closeModal: "關閉",
          openBillingPage: "前往購買額度",
          checkoutSuccess: "Stripe 已確認支付。若你修改了付費名額數量，現在可以重新嘗試匯入 CSV。",
          checkoutCancelled: "Stripe 支付已取消，本次未變更任何計費資訊。",
          checkoutUpdated: "Stripe 訂閱已更新，現在可以重新嘗試匯入 CSV。",
        },
        importResult: (
          successRows: number,
          createdVehicles: number,
          failedRows: number,
          skippedRows = 0,
        ) =>
          `已匯入 ${successRows} 行，新增 ${createdVehicles} 台車，跳過 ${skippedRows} 行，另有 ${failedRows} 行待人工檢查。`,
        reclaimedIdentifiers: (pairs: string) =>
          `已從錯誤的車輛上收回 VIN / Turo 車輛 ID:${pairs}。這兩個標識在匯入時優先順序高於車牌,在收回之前行程一直被歸到錯誤的車上。`,
      },
    },
    turoCsvFields: {
      title: "Turo CSV 資料",
      hint: "這筆訂單在 Turo 匯出檔案裡那一行的全部欄位。可以選擇顯示哪些，所有訂單一起生效。",
      edit: "選擇欄位",
      done: "完成",
      showAll: "全部顯示",
      hiddenCount: (count: number) => `已隱藏 ${count} 個欄位`,
      emptyHidden: "（空）",
      saveFailed: "沒儲存上，請再試一次。",
    },
  } as const;
