// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/imports.ts.
// Do not edit: change the Simplified text there and re-run the script.

export const importsMessages = {
    imports: {
      pageKicker: "CSV 匯入",
      pageTitle: "匯入 Turo 行程",
      pageSubtitle: "按四個步驟，把 Turo 收益匯出檔案同步進這個工作台。",
      guideTitle: "匯入步驟",
      guideSteps: [
        {
          title: "從 Turo 下載 CSV",
          body: "開啟 Turo 的 Earnings 頁面，選擇你想匯入的時間範圍，點選 Export 把 CSV 下載到電腦。",
        },
        {
          title: "確認名額夠用",
          body: "先看右側「當前可用總名額」是否覆蓋車隊數量。不夠的話，先去購買更多名額或輸入 coupon 解鎖。",
        },
        {
          title: "上傳並對映欄位",
          body: "點選「選擇檔案」上傳 CSV，系統會自動匹配常見列名。Reservation ID 是必填項，也是唯一的重複訂單判斷依據。",
        },
        {
          title: "執行匯入",
          body: "點選「執行匯入」。新車輛會自動建檔（除非關閉該選項），與線下訂單衝突的記錄會被標記等你處理。",
        },
      ],
      unconfirmedKicker: "需要核對",
      unconfirmedTitle: (count: number) => `${count} 個即將開始的訂單,車輛未經車牌確認`,
      unconfirmedCopy:
        "預訂郵件裡只有車型,從來沒有車牌,所以這些訂單的車輛是拿車型去車隊裡匹配出來的。只有在車隊完整時這才成立:如果真正那台車不在車隊裡,車型仍然可能唯一匹配到另一台車——錯的那台——而結果看上去和正確答案沒有任何區別。匯入覆蓋這些日期的 CSV,車牌就能定案。",
      unconfirmedSiblings: (count: number) => `車隊裡有 ${count} 台同款同年份`,
      unconfirmedUnknownVehicles: (list: string) =>
        `以前的匯入裡出現過車隊中沒有的車:${list}。只要它們不在車隊裡,這些車型的預訂郵件能匹配到的車就比實際少一台,就可能落到錯誤的車上。重新匯入時勾選「自動建立缺失車輛」,或者手動把它們加進來。`,
      unconfirmedShowList: (count: number) => `檢視這 ${count} 筆`,
      logShowAll: (count: number) => `顯示更早的 ${count} 次匯入`,
      logKicker: "匯入日誌",
      logTitle: "最近 CSV 批次",
      sampleFile: "示例檔案位於 `/sample-data/turo-sample.csv`",
      table: {
        file: "檔案",
        importedBy: "匯入人",
        importedAt: "匯入時間",
        rows: "行數",
        result: "結果",
        batchResult: (successRows: number, failedRows: number) =>
          `${successRows} 成功 / ${failedRows} 失敗`,
      },
      panel: {
        uploadKicker: "1. 上傳 CSV",
        uploadTitle: "匯入前預覽",
        openTuroPage: "開啟 Turo 下載頁",
        chooseFile: "選擇檔案",
        emptyState: "上傳 `/sample-data/turo-sample.csv` 示例檔案，或真實的 Turo 匯出檔案後，這裡會顯示對映預覽。",
        mappingKicker: "2. 欄位對映",
        mappingWaiting: "等待上傳檔案。",
        importKicker: "3. 開始匯入",
        ignoreColumn: "忽略該列",
        rowsDetected: "識別到行數",
        requiredMappingLeft: "仍缺少的必填對映",
        none: "無",
        oneVehicleIdentifier: "至少一個車輛標識欄位",
        turoAccountTitle: "這份檔案屬於哪個 Turo 帳戶",
        turoAccountHint:
          "主帳戶留空。代管帳戶的匯出必須填帳戶名，否則它的車會被當成主帳戶車輛，之後再也匹配不上自己的 Turo 郵件。",
        turoAccountPlaceholder: "例如 kevin",
        turoAccountMain: "主帳戶",
        turoAccountOther: "其他帳戶…",
        autoCreateTitle: "自動從 CSV 建立缺失車輛",
        autoCreateHint: "首次匯入真實 Turo earnings 匯出時建議開啟。",
        runImport: "執行匯入",
        importing: "匯入中...",
        genericFailure: "匯入失敗",
        importSuccessTitle: "匯入完成",
        importFailureTitle: "匯入失敗",
        importAlertClose: "關閉",
        billing: {
          kicker: "0. 訂閱計費",
          title: "車輛名額訂閱",
          copy: "前 5 台車輛免費。超過後，每多 1 台車輛收費 $1 USD / 月。只有已購買名額覆蓋車輛總數後，才允許匯入 CSV。",
          currentVehicles: "當前車輛數",
          freeIncluded: "免費名額",
          paidSlots: "已付費名額",
          allowedTotal: "當前可用總名額",
          subscriptionStatus: "訂閱狀態",
          desiredSlots: "想購買的車輛名額數",
          priceHint: (value: string) => `超出免費 5 台後的月費：${value}`,
          payAction: "前往 Stripe 支付",
          manageAction: "去 Stripe 修改名額",
          redirecting: "正在跳轉到 Stripe...",
          notConfigured: "Stripe 計費尚未配置，暫時無法啟用這個功能。",
          genericError: "暫時無法發起支付，請稍後再試。",
          projectionTitle: "匯入前計費檢查",
          projectedVehicles: (count: number) => `匯入後預計車輛數：${count}`,
          projectedNewVehicles: (count: number) => `本次檔案新增車輛數：${count}`,
          projectedPaidSlots: (count: number) => `匯入後所需付費名額：${count}`,
          checkingImport: "正在檢查這份 CSV 是否超過已購車輛名額...",
          limitExceeded: "車輛數量將超過當前已購名額，請先補交費用再匯入。",
          limitExceededDetail: (projected: number, allowed: number, extra: number) =>
            `這份 CSV 會讓車輛總數達到 ${projected} 台，但你當前只允許 ${allowed} 台。請先補購 ${extra} 個付費名額。`,
          modalKicker: "需要補交費用",
          modalTitle: "購買更多車輛名額",
          modalCopy: (projected: number, allowed: number) =>
            `這次匯入會讓你的車輛總數達到 ${projected} 台，而當前已付費上限只支援 ${allowed} 台。請先完成支付，再重新執行匯入。`,
          projectedVehiclesLabel: "預計匯入後車輛數",
          additionalNeededLabel: "還需補購名額",
          modalPriceHint: (value: string) => `迴圈月費：${value}`,
          closeModal: "關閉",
          openBillingPage: "前往購買額度",
          checkoutSuccess: "Stripe 已確認支付。若你修改了付費名額數量，現在可以重新嘗試匯入 CSV。",
          checkoutCancelled: "Stripe 支付已取消，本次未變更任何計費資訊。",
          checkoutUpdated: "Stripe 訂閱已更新，現在可以重新嘗試匯入 CSV。",
        },
        importResult: (
          successRows: number,
          createdVehicles: number,
          failedRows: number,
          skippedRows = 0,
        ) =>
          `已匯入 ${successRows} 行，自動建立 ${createdVehicles} 台車輛，跳過 ${skippedRows} 行，另有 ${failedRows} 行待人工檢查。可重新整理下方日誌檢視新批次。`,
        archivedRows: (count: number) =>
          `已跳過 ${count} 行歸檔車輛的資料 —— 歸檔的作用就是讓它們不再被更新。`,
        reclaimedIdentifiers: (pairs: string) =>
          `已從錯誤的車輛上收回 VIN / Turo 車輛 ID:${pairs}。這兩個標識在匯入時優先順序高於車牌,在收回之前行程一直被歸到錯誤的車上。`,
        selectedVehiclesSummary: (selected: number, max: number) =>
          `已選擇 ${selected} / ${max} 台新車輛，符合當前額度上限。`,
        selectedVehiclesHint:
          "這份 CSV 裡已存在於系統中的車輛仍會正常同步，只有新車輛會佔用剩餘額度。",
        chooseVehiclesTitle: "選擇本次要匯入的新車輛",
        chooseVehiclesCopy: (max: number) =>
          `這份檔案裡的新車輛數量超過了當前剩餘額度。你現在可以先勾選最多 ${max} 台新車輛匯入，或者先補購更多額度。`,
        chooseVehiclesLabel: "這份 CSV 識別到的新車輛",
        importSelectedAction: "匯入已選車輛",
        selectionLimitNotice: (max: number) => `當前最多可選擇 ${max} 台新車輛。`,
        selectionNoneAvailable:
          "當前沒有可用的新車輛額度。你仍然可以匯入這份檔案裡已存在於系統中的車輛，或者先去補購額度。",
      },
    },
  } as const;
