// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/investment-ranking.ts.
// Do not edit: change the Simplified text there and re-run the script.

export const investmentRankingMessages = {
    investmentRanking: {
      metaTitle: "買哪台車 · TATO",
      metaDescription:
        "基於自有車隊溫哥華出租資料與運營成本，對車型投資回報率進行排名。",

      kicker: "溫哥華 · 投資回報",
      title: "買哪台車最划算？",
      intro:
        "對所有可上架的車型和年份評分：能賺多少，對比買車、養車、修車和最終賣車的代價。按固定預算排名。",

      budgetLabel: "預算",
      budgetHint: "用於計算「可買台數」和「預算總回報」。",
      perspectiveLabel: "算誰的回報",
      perspectiveTato: "TATO 自己買車",
      perspectiveOwner: "車主與我們合作",
      commissionLabel: "管理分成",
      sortLabel: "排序依據",
      sortTotalRoi: "總回報率",
      sortCashYield: "現金回報率",
      sortNetCash: "年淨現金",
      sortBudgetReturn: "整個預算的總回報",
      priceRangeLabel: "車價區間",
      minPrice: "最低",
      maxPrice: "最高",

      assumptionsToggle: "成本假設",
      insuranceLabel: "保險 / 年",
      parkingLabel: "停車 / 年",
      licensingLabel: "牌照等 / 年",
      assumptionsNote:
        "這些是每台車的固定成本，對便宜車的壓力最大。正因為有它們，排名才不會退化成「無腦買最便宜的車」——請改成你實際支付的金額。",
      resetAssumptions: "恢復預設值",

      colRank: "#",
      colVehicle: "車型",
      colPrice: "車價",
      colRevenue: "年收入",
      colCosts: "運營成本",
      colNet: "年淨現金",
      colRoi: "總回報率",
      colRange: "最壞 – 最好",
      colUnits: "台數",
      colBudgetReturn: "預算總回報",

      detailTitle: "這個數字是怎麼算出來的",
      detailRevenue: "Turo 總收入",
      detailCommission: "減去管理分成",
      detailMaintenance: "常規保養",
      detailRepairs: "預期維修",
      detailFixed: "保險、停車、牌照",
      detailNetCash: "年淨現金",
      detailDepreciation: "折舊",
      detailTotal: "年度總回報",
      detailKm: "預計行駛里程",
      detailPayback: "回本週期",
      detailPaybackYears: "{years} 年",
      detailPaybackNever: "按此速度無法回本",
      detailPriceLabel: "購車價",
      detailPriceHint:
        "由車齡、品牌和原始廠商指導價推算。建議填入你實際看到的報價——整個排名對這個數字的敏感度高於頁面上任何其他輸入。",
      detailPriceReset: "改用模型估值",
      detailEvidenceDirect: "這款車我們在運營：{months} 個「車-月」實際資料。",
      detailEvidenceSegment: "我們沒運營過這款車，由同類車型推算。",

      summaryScored:
        "已評分 {scored} 個「車型+年份」組合。{positive} 個期望回報為正，其中 {robust} 個在最壞情況下仍為正。",
      emptyTitle: "沒有符合篩選條件的車型",
      emptyCopy: "放寬車價區間或提高預算。",

      cautionTitle: "看排名之前，先看這幾條",
      caution1:
        "車價是模型推算的，不是真實報價。它是所有數字的分母——買車前務必核對實際成交價。",
      caution2:
        "維修成本來自公開的品牌平均值，不是我們自己的維修單據。這是誤差最大的一項，做決策請按「最壞情況」那一列考慮。",
      caution3: "收入假設車輛由我們託管、基本全時段可租，並採用我們目前的定價策略。",
      caution4:
        "帳面上買幾台便宜車一定勝過買一台貴車。頁面已經給每台車計入了各自的保險和停車，但沒有計入你的時間和精力。",
    },
  } as const;
