// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/rental-estimate.ts.
// Do not edit: change the Simplified text there and re-run the script.

export const rentalEstimateMessages = {
    valuation: {
      title: "車輛投資回報",
      tabFleet: "車隊表現",
      tabEstimate: "租金預估",
      tabRanking: "買車排名",

      statMonth: "本月車隊收益",
      statPerKm: "車隊每公里收益",
      statPerKmDistance: "已統計 {km} 公里",
      statPerKmNoDistance: "暫無行駛距離資料",
      statPriced: "已填購車價",

      searchPlaceholder: "搜尋車牌、暱稱、品牌、車型、年份或車主",
      searchCount: "{shown} / {total}",
      searchEmpty: "沒有匹配「{query}」的車輛。",
      empty: "目前還沒有可分析的車輛。",

      colVehicle: "車輛",
      colTrend: "近 6 個月",
      colMonth: "本月",
      colTtm: "近 12 個月",
      colPerKm: "每公里",
      colDistance: "里程",
      colRoi: "年化回報",
      colPrice: "購車價",
      unassignedOwner: "未分配",
      pricePlaceholder: "填寫價格",
      priceSave: "儲存",
      priceSaving: "儲存中…",
      roiNeedsPrice: "填寫購車價後才能計算年化回報。",
      footnote:
        "金額為扣除 Turo 分成後的淨收益。每公里收益只計有里程錶讀數的訂單；年化回報 = 近 12 個月淨收益 ÷ 購車價。",
    },
    rentalEstimate: {
      makeLabel: "品牌",
      modelLabel: "車型",
      yearLabel: "年份",
      makePlaceholder: "選擇品牌",
      modelPlaceholder: "選擇車型",
      modelNeedsMake: "請先選擇品牌",
      yearHint: "Turo 加拿大隻接受車齡 12 年以內的車，即 {oldest} 年及以後。",

      emptyTitle: "選擇車型後顯示預估結果",
      emptyCopy: "已收錄 360 款加拿大在售車型，覆蓋 Turo 加拿大允許上架的全部年份。",

      headlineLabel: "預計第一年收入",
      headlineRange: "通常在 {low} – {high} 之間",
      grossLabel: "Turo 平台總收入",
      netLabel: "車主到手",
      commissionLabel: "TATO 管理分成",
      commissionHint:
        "拖動以匹配你拿到的合作條件。「車主到手」是打給你的金額，尚未扣除你自己的成本——保險、貸款、保養、折舊。",

      chartTitle: "未來 12 個月月度收入預估",
      chartHint: "柱高為 Turo 平台總收入，深色部分為車主到手。",

      statPeak: "旺季月份",
      statTrough: "淡季月份",
      statAverage: "月均收入",
      statValue: "車輛估值",
      statPeakRatio: "是淡季的 {ratio} 倍",

      evidenceDirectTitle: "這款車我們在運營",
      evidenceDirect:
        "該預估基於我們自己運營 {model} 的 {months} 個「車-月」實際資料，並結合全車隊規律校準。",
      evidenceSegmentTitle: "由同類車型推算",
      evidenceSegment:
        "我們沒有運營過 {model}。該預估來自同等價值、同類車身的車輛在我們車隊中的表現規律——這套規律在留一驗證中，{within} 的車年度誤差在 20% 以內。",
      evidenceExtrapolated: "這款車的價值超出我們實際運營過的區間，結果僅供參考，不構成報價。",

      methodTitle: "預估方法",
      methodToggleOpen: "檢視計算方法",
      methodToggleClose: "收起計算方法",
      methodBasis:
        "基於 {trips} 筆已完成的 Turo 訂單，覆蓋 {vehicles} 台車、{models} 款車型，時間跨度 {from} 至 {to}，全部為大溫地區實際出租記錄。",
      methodPoint1Title: "車輛價值決定基準，但影響遠小於直覺",
      methodPoint1:
        "月收入隨車輛價值上升的彈性係數為 0.42：車價翻倍，收入只增加約 34%，而不是翻倍。這就是為什麼便宜的 MPV 和皮卡的投資回報率高於豪華 SUV。",
      methodPoint2Title: "車身型別再做一次修正",
      methodPoint2:
        "在同等價值下，MPV 和皮卡比車隊基準線高約 9%，豪華轎車低 11%，電動車低 17%。",
      methodPoint3Title: "溫哥華的季節性是最大的單一變數",
      methodPoint3:
        "7、8 月約為平均月份的 1.9 倍，11 月只有一半左右。這個形狀在 2024、2025、2026 三年完全重複出現——所以只給一個年度數字會誤導，這個頁面畫 12 根柱子。",
      methodPoint4Title: "準確度",
      methodPoint4:
        "採用留一交叉驗證（每次剔除一台車，用其餘車輛預測它）：第一年總收入的中位誤差為 {error}，{within} 的車落在 20% 誤差以內。單個月份波動更大——一筆長租就能顯著改變某個月。",

      assumptionsTitle: "預估的前提假設",
      assumption1: "車輛由 TATO 託管，基本全時段上架可租。",
      assumption2: "定價採用我們目前實際執行的動態價格策略，含適用情況下的機場送取車。",
      assumption3:
        "金額為加元計價的租金總收入，未扣除保險、貸款、保養、清潔、停車、折舊與稅費。",
      assumption4: "歷史表現不構成承諾。市場需求、同行競爭和平台政策都會變化。",

      downloadAction: "下載 PDF 報告",
      downloadingAction: "正在生成…",
      downloadFailed: "PDF 生成失敗，請重試。",
      reportTitle: "車輛租金收入預估",
      reportVehicleValue: "車輛估值",
      reportGeneratedAt: "生成於 {date}",
      reportEvidenceDirect: "該預估基於我們自己運營這款車型的 {months} 個「車-月」實際資料。",
      reportEvidenceSegment: "該預估來自同等價值、同類車身的車輛在我們車隊中的表現規律。",
      reportBasis:
        "基於 {trips} 筆已完成的 Turo 訂單，覆蓋 {vehicles} 台車，時間跨度 {from} 至 {to}，全部為大溫地區實際出租記錄。採用留一交叉驗證，第一年總收入的中位誤差為 {error}。",
    },
  } as const;
