// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/turo-updates.ts.
// Do not edit: change the Simplified text there and re-run the script.

export const turoUpdatesMessages = {
    turoUpdates: {
      kicker: "動態",
      title: "Turo 動態更新",
      copy: "Turo 發來的所有郵件，每條一句話概要。看這裡就不用去翻郵箱。",
      empty: "還沒有收到任何動態。",
      today: "今天",
      yesterday: "昨天",
      all: "全部",
      unreadOnly: "待回覆",
      countLabel: (n: number) => `${n} 條動態`,
      openOnTuro: "去 Turo 檢視",
      viewOrder: "訂單",
      viewThread: "會話",
      kinds: {
        GUEST_MESSAGE: "客人訊息",
        BOOKING_CREATED: "新訂單",
        BOOKING_MODIFIED: "訂單變更",
        BOOKING_CANCELLED: "訂單取消",
        TRIP_STARTED: "已取車",
        TRIP_ENDED: "已還車",
        PAYOUT: "打款",
        SUPPORT: "客服",
        OTHER: "其他",
      },
    },
  } as const;
