/**
 * Generate the Traditional Chinese message blocks from the Simplified ones.
 *
 *   npx tsx scripts/generate-zh-hant.ts          write lib/i18n/zh-hant/*
 *   npx tsx scripts/generate-zh-hant.ts --check  fail if they are stale (CI)
 *
 * Every module in `lib/i18n/messages/` exports `{ en: {...}, zh: {...} }`.
 * This takes the *source text* of each `zh` block and runs it through
 * OpenCC (Simplified → Taiwan standard, with Taiwan phrasing), so the
 * output is written once, reviewed in the diff, and costs nothing at
 * runtime.
 *
 * Converting source text rather than values is what makes message
 * functions come out right. `(name) => \`${name} 的行程\`` is a function
 * at runtime, and the old per-character converter could only pass it
 * through untouched -- so every parameterised string in the Traditional
 * UI used to render in Simplified. Here the template text is just text.
 *
 * OpenCC only rewrites CJK characters, so identifiers, English and the
 * surrounding code survive unchanged.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync } from "node:fs";
import path from "node:path";

import ts from "typescript";

import { convertUiToTraditional as convertSource } from "../lib/zh-hant-convert";

const SOURCE_DIR = path.join(process.cwd(), "lib/i18n/messages");
const OUTPUT_DIR = path.join(process.cwd(), "lib/i18n/zh-hant");

type Block = { name: string; text: string };

function findZhBlocks(fileName: string, source: string): Block[] {
  const file = ts.createSourceFile(fileName, source, ts.ScriptTarget.Latest, true);
  const blocks: Block[] = [];

  for (const statement of file.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    const exported = statement.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
    if (!exported) continue;

    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || !declaration.initializer) continue;
      let initializer: ts.Expression = declaration.initializer;
      if (ts.isAsExpression(initializer)) initializer = initializer.expression;
      if (!ts.isObjectLiteralExpression(initializer)) continue;

      const zh = initializer.properties.find(
        (property): property is ts.PropertyAssignment =>
          ts.isPropertyAssignment(property) &&
          (ts.isIdentifier(property.name) || ts.isStringLiteral(property.name)) &&
          property.name.text === "zh",
      );
      if (!zh) continue;
      blocks.push({ name: declaration.name.text, text: zh.initializer.getText(file) });
    }
  }

  return blocks;
}

function render(sourceFile: string, blocks: Block[]) {
  const header = [
    `// GENERATED by scripts/generate-zh-hant.ts from lib/i18n/messages/${sourceFile}.`,
    "// Do not edit: change the Simplified text there and re-run the script.",
    "",
  ].join("\n");
  const body = blocks
    .map((block) => `export const ${block.name} = ${convertSource(block.text)} as const;\n`)
    .join("\n");
  return `${header}\n${body}`;
}

function main() {
  const check = process.argv.includes("--check");
  const files = readdirSync(SOURCE_DIR)
    .filter((file) => file.endsWith(".ts"))
    .sort();

  const outputs = new Map<string, string>();
  const indexLines = [
    "// GENERATED by scripts/generate-zh-hant.ts. Do not edit.",
    "",
  ];

  for (const file of files) {
    const source = readFileSync(path.join(SOURCE_DIR, file), "utf8");
    const blocks = findZhBlocks(file, source);
    if (blocks.length === 0) continue;
    const base = file.replace(/\.ts$/, "");
    outputs.set(`${base}.ts`, render(file, blocks));
    indexLines.push(`export * from "./${base}";`);
  }
  outputs.set("index.ts", `${indexLines.join("\n")}\n`);

  const stale: string[] = [];
  if (!check) mkdirSync(OUTPUT_DIR, { recursive: true });

  for (const [file, content] of outputs) {
    const target = path.join(OUTPUT_DIR, file);
    const current = existsSync(target) ? readFileSync(target, "utf8") : null;
    if (current === content) continue;
    if (check) stale.push(file);
    else writeFileSync(target, content);
  }

  // A messages module that was deleted leaves an orphan behind.
  if (existsSync(OUTPUT_DIR)) {
    for (const file of readdirSync(OUTPUT_DIR)) {
      if (outputs.has(file)) continue;
      if (check) stale.push(file);
      else unlinkSync(path.join(OUTPUT_DIR, file));
    }
  }

  if (check && stale.length > 0) {
    console.error(
      `Traditional Chinese messages are stale: ${stale.join(", ")}.\n` +
        "Run `npx tsx scripts/generate-zh-hant.ts` and commit the result.",
    );
    process.exit(1);
  }
  if (!check) console.log(`Wrote ${outputs.size} files to lib/i18n/zh-hant.`);
}

main();
